apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hag-admin
  namespace: helsearbeidsgiver
spec:
  azure:
    application:
      enabled: true
      sidecar:
        enabled: true
      allowAllUsers: false
      claims:
        groups:
          -id: "e3ab1801-e5a6-48ca-9c3b-5a91ce182c57"
  accessPolicy:
    outbound:
      rules:
        - application: notifikasjon-produsent-api
          namespace: fager
  env:
    - name: ARBEIDSGIVER_NOTIFIKASJON_API_URL
      value: "http://notifikasjon-produsent-api.fager/api/graphql"
    - name: ARBEIDSGIVER_NOTIFIKASJON_SCOPE
      value: "api://dev-gcp.fager.notifikasjon-produsent-api/.default"
  ingresses:
    - https://hag-admin.intern.dev.nav.no
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  secureLogs:
    enabled: true