apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hag-admin
  namespace: helsearbeidsgiver
spec:
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      {{#if login}}
      allowAllUsers: false
      claims:
        groups:
          - id: e3ab1801-e5a6-48ca-9c3b-5a91ce182c57
    sidecar:
      enabled: true
      autoLogin: true
    {{/if}}
  accessPolicy:
    outbound:
      rules:
        - application: notifikasjon-produsent-api
          namespace: fager
        - application: logging
          namespace: nais-system
  env:
    - name: ARBEIDSGIVER_NOTIFIKASJON_API_URL
      value: "http://notifikasjon-produsent-api.fager/api/graphql"
    - name: JDK_JAVA_OPTIONS
      value: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Xmx32M
    {{#each env as |var|}}
    - name: {{ var.name }}
      value: "{{ var.value }}"
    {{/each }}
  ingresses:
    {{#each ingresses as |url|}}
      - {{ url }}
    {{/each}}
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 250m
      memory: 64Mi
  observability:
    logging:
      destinations:
        - id: loki
