apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hag-admin
  namespace: helsearbeidsgiver
spec:
  ingresses:
    - https://hag-admin.intern.dev.nav.no
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi